### ISSUE TITLE
Dispatcher implementation not compatible with Bus interface

### ISSUE THREAD

**Issue by StevenBock** [LaravelCollective/bus#13]
After upgrading to the 5.3 branch of Laravel and this package, I am receiving the following error:

`PHP Fatal error:  Declaration of Collective\Bus\Dispatcher::dispatchNow($command, Closure $afterResolving = NULL) must be compatible with Illuminate\Contracts\Bus\Dispatcher::dispatchNow($command, $handler = NULL)`

It looks like the interface was recently updated in the commit below:

[https://github.com/laravel/framework/commit/1eade8052e571cee59e3e9eb89762943e186aa1b](https://github.com/laravel/framework/commit/1eade8052e571cee59e3e9eb89762943e186aa1b)

**Comment by marklj** [comment]
I'm having this same issue.

**Comment by kingsloi** [comment]
Me too!

**Comment by GrahamCampbell** [comment]
You can use https://github.com/AltThree/Bus for a L5.3 version, or simply just switch back to Laravel 5.3's native stuff. We've added back the way to define handlers to the core, it's not not an automatic mapping. My alt three package just plugs that gap with a L5.1 like mapping registration.

**Comment by GrahamCampbell** [comment]
Here's a usage example from a real app:

![image](https://cloud.githubusercontent.com/assets/2829600/18108568/b42dadd8-6f04-11e6-8bee-dc000084b783.png)

**Comment by JeroenVranken** [comment]
Getting the same error as well, right after upgrading to Laravel 5.3 and Collective\Bus 5.3

**Comment by omadoyeabraham2** [comment]
I had this same issue and temporarily fixed it by going to \vendor\laravelcollective\bus\src\Dispatcher.php and removing the Closure binding from the $afterResolving parameter of the dispatchNow function.

I'm not sure though if this is secure, and if it won't break any other functionality in the framework.

Any thoughts on this?

**Comment by kavin-90** [comment]
I had same issue :cry:

**Comment by nWidart** [comment]
Same issue here.

**Comment by gvlatko** [comment]
there is an PR open for this.

**Comment by GrahamCampbell** [comment]
As I've said already, this is a non-issue since there already exists another package that mimics L5.1 behaviour on L5.3, and other than that, you don't need this package, because the features that were removed in 5.2 are **RESTORED TO THE CORE** in L5.3.

**Comment by gvlatko** [comment]
It's like talking to a parrot...

**Comment by spronkey** [comment]
@GrahamCampbell Are you able to point us to the core docs for 5.3 that cover this? I've had a look through and can't find anything.

**Comment by gvlatko** [comment]
He is building a career based on his github popularity so don't expect a
proper answer except that his library is the solution to world hunger.

**Comment by kingsloi** [comment]
@spronkey, it's not in the docs anymore (not since v5), the only thing I could find on the bus is the API docs: https://laravel.com/api/5.3/Illuminate/Bus.html

**Comment by GrahamCampbell** [comment]
> Are you able to point us to the core docs for 5.3 that cover this? I've had a look through and can't find anything.

I've already pointed you to github.com/AltThree/Bus that mimics the 5.1 style bus on laravel 5.3, and provides a replacement, similar to this package for laravel 5.2.

**Comment by GrahamCampbell** [comment]
If you read the source code for https://github.com/AltThree/Bus/blob/master/src/Dispatcher.php, it should become immidately clear how it works.

**Comment by gvlatko** [comment]
And there it is :)

**Comment by GrahamCampbell** [comment]
Speaking frankly, I'm not sure why this issue is still open, because there is already a solution. This package works great on laravel 5.2, but it's totally unsuitable for Laravel 5.3, by design. This is not a simple patch it up and ship it problem.

**Comment by GrahamCampbell** [comment]
On laravel 5.3+, you could use that other package, or just no package at all, since 5.3 **brings back the features needed from 5.1**, and the alt thee package just wraps them in a similar, but not identical, way to how it worked in 5.1.

**Comment by gvlatko** [comment]
And this kids, is how you add 3 contributions to your github profile in one
minute. Gotta stay on top!

**Comment by spronkey** [comment]
@GrahamCampbell Offering an alternative package is fine and sometimes helpful. But in this case, a cursory look at this package shows it has scant documentation and will require a decent time investment into reading source code to see what it does and whether it's actually suitable for my particular use case.

Regardless, you've made a claim that 5.3 brings back features from 5.1, It would be helpful if you could explain what 5.3 brought back, as I've looked through the docs and release notes for 5.3 and can't see any mention of restoration of Commands, Commands with separate handlers, handler resolution etc.

@gvlatko Agreed, it's poor form.

**Comment by gvlatko** [comment]
as a side note: https://github.com/LaravelCollective/bus/pull/14

**Comment by GrahamCampbell** [comment]
Yeh, that PR doesn't work, because you need to basically start again to get it working, since the internals are totally different. Anyway, I'm unwatching this repo now.

**Comment by HectorOrdonez** [comment]
Already spent half an hour trying to figure out what I am supposed to do with this now. No docs on this alternative package either. This is really bad.

**Comment by gvlatko** [comment]
@HectorOrdonez wait for it. Graham will show up, copy paste the same sentence (to use his package) and add another contribution to his Github profile.

of course it won't be of any help to you.

**Comment by gordonchanhk** [comment]
Upon upgrade to L5.3 from L5.2, I removed this module from package.json and error gone.

**Comment by nikhilbhatia22** [comment]
> Upon upgrade to L5.3 from L5.2, I removed this module from package.json and error gone.

Yes, correct, upgrading from L5.2 to L5.3, 
1. Remove this `collective/bus` package from your `composer.json`, 
2. update your `config/app.php` to have Illuminate based `BusServiceProvider`
3. Remove `SelfHandling` Contract, if still present on your jobs.

Done, your jobs should work flawlessly.
