### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by rdehnhardt** [LaravelCollective/bus#17]
Enable support for Laravel 5.4

**Comment by daniesy** [comment]
+1

**Comment by mlantz** [comment]
Looking into the old 5.3 issue before I move this forward, expect a few days yet, sorry all

**Comment by james-coder** [comment]
+1, before 5.5 please :+1: 

https://www.joeferguson.me/laravel-release-schedule/

**Comment by rajangupta24** [comment]
Need support for 5.4
